name: orbitals
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - flask
  - plotly
  - qutip
  - mdanalysis
  - openbabel
  - chembl_webresource_client
  - psutil
  - pip
  - pip:
    - werkzeug 