name: orbitals
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - flask
  - plotly
  - mdanalysis
  - openbabel
  - chembl_webresource_client
  - psutil
  - scikit-learn
  - pandas
  - rdkit
  - ase
  - pymatgen
  - pip
  - pip:
    - gunicorn
    - werkzeug
