name: orbitals
channels:
  - conda-forge
  - openbabel
dependencies:
  - python=3.9
  - numpy
  - scipy
  - flask
  - plotly
  - chembl_webresource_client
  - mdanalysis
  - ase
  - pymatgen
  - rdkit
  - psutil
  - openbabel
  - pip
  - pip:
    - scikit-image
    - gunicorn
    - werkzeug
